# Generated by Django 3.0 on 2020-10-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_delete',
            field=models.IntegerField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='relic',
            name='is_delete',
            field=models.IntegerField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.IntegerField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='video',
            name='is_delete',
            field=models.IntegerField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=32),
        ),
    ]
