# Generated by Django 3.0 on 2020-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201022_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relic',
            name='picture',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='relic',
            name='relic_file',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
