# Generated by Django 3.1.2 on 2021-03-14 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
