# Generated by Django 3.1.2 on 2021-03-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210322_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=128)),
                ('person', models.IntegerField(default=0, max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_delete',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
