# Generated by Django 3.1.2 on 2021-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210323_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='relic',
            field=models.IntegerField(default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
