# Generated by Django 3.1.2 on 2021-03-24 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210323_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='relic',
            field=models.IntegerField(default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='is_delete',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
