# Generated by Django 3.1.2 on 2021-03-24 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210324_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='relic',
            new_name='relic_id',
        ),
        migrations.AddField(
            model_name='video',
            name='relic_name',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relic',
            name='relic_name',
            field=models.CharField(max_length=128),
        ),
    ]
