# Generated by Django 3.1.2 on 2021-03-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210324_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='relic_name',
            new_name='relic',
        ),
    ]
